# Generated by Django 3.2.6 on 2021-08-29 16:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banxico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_date', models.DateField()),
                ('dollar_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
            ],
            options={
                'verbose_name': 'banxico',
                'verbose_name_plural': 'banxico',
                'ordering': ['last_date'],
            },
        ),
    ]
