# Generated by Django 3.2.6 on 2021-08-28 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='total_sell',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='type',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\w{8,40}', 'the type should be be alphanumeric from 8 to 40 characters.')]),
        ),
    ]
