# Generated by Django 3.2.6 on 2021-08-28 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_api', '0003_auto_20210827_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='type',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\w{8,40}', 'The type should be be alphanumeric from 8 to 40 characters.')]),
        ),
    ]
