# Generated by Django 3.2.6 on 2021-08-29 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_api', '0005_alter_bond_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='type',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^(\\d|[a-zA-Z]){8,40}$', 'The type should be be alphanumeric from 8 to 40 characters.')]),
        ),
    ]
